version: '3.8'

services:
  frontend:
    container_name: frontend-vuejs
    build:
      context: ./front-end
      dockerfile: Dockerfile 
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    container_name: backend-python
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    
# version: '3'

# services:
#   frontend:
#     image: tranhuynhtanphat/frontend-image:v1
#     container_name: frontend-vuejs
#     ports:
#       - 80:80
#     restart: unless-stopped
#     depends_on:
#       - backend

#   backend:
#     image: tranhuynhtanphat/backend-image:v1
#     container_name: backend-python
#     ports:
#       - 8000:8000
#     restart: unless-stopped

  