version: '3.8'

services:
  frontend:
    container_name: frontend-vuejs
    build:
      context: ./front-end
      dockerfile: Dockerfile 
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    container_name: backend-python
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    
