version: '3.8'
services:
  app:
    container_name: frontend-vuejs
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules  
    ports:
      - "8080:8080"