name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install --no-cache-dir -r back-end/requirements.txt

      - name: Build Backend Docker Image
        run: docker build -t backend-image back-end
      
      - name: Change tag BE Docker Image
        run: docker tag backend-image ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:v1

      - name: Build Frontend Docker Image
        run: docker build -t frontend-image front-end

      - name: Change tag FE Docker Image
        run: docker tag frontend-image ${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-image:v1

      - name: Push Frontend Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-image:v1

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-208-115-16.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose down
            docker-compose pull
            docker-compose up -d
